# Default values for workflow.
nameOverride: workflow
replicaCount: 1
dockerregistrynamespace:
dockerregistry:
identity:
  clientid:
  resourceid:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
reason: unknown
serviceuri:
  delivery: http://delivery/api/Deliveries/
  drone: http://dronescheduler/api/DroneDeliveries/
  package: http://package/api/packages/
servicerequest:
  maxretries: 3
  circuitbreakerthreshold: 0.5
  circuitbreakersamplingperiodseconds: 5
  circuitbreakerminimumthroughput: 20
  circuitbreakerbreakduration: 30
  maxbulkheadsize: 100
  maxbulkheadqueuesize: 25
healthcheck:
  delay:
readinessProbe:
  exec:
    command:
    - cat
    - /app/healthz
  initialDelaySeconds: 40
  periodSeconds: 15
  timeoutSeconds: 2
  failureThreshold: 5
livenessProbe:
  exec:
    command:
    - find
    - /app/healthz
    - -mmin
    - -1
  initialDelaySeconds: 50
  periodSeconds: 30
keyvault:
  name:
  resourcegroup:
  subscriptionid:
  tenantid:
telemetry:
  level: "Error"
tags:
  dev: false
  prod: false
  qa: false
  staging: false
