# QA values for package.
nameOverride: package
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: Always
    log:
      level: "info"
    reason: "new qa deploy"
    current: true
    ingress:
      class: "nginx-qa"
    resources:
      requests:
        cpu: 90m
        memory: 100Mi
      limits:
        cpu: 130m
        memory: 140Mi
