#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# ingress
###################################################################################################
{{- $svcversion := .Chart.AppVersion | replace "." "" }}
{{- $appversion := .Chart.AppVersion }}
{{- $defaultversionedpath := printf "/%s/" $appversion }}
{{- $relname := .Release.Name }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $relname }}-ingress
  annotations:
    kubernetes.io/ingress.class: {{ required "ingress.class is required" .Values.ingress.class | quote }}
    nginx.ingress.kubernetes.io/rewrite-target: /api/deliveries/public$1
spec:
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.hosts }}
  {{- if .tls }}
  - hosts:
    - {{ .name }}
    secretName: {{ $relname }}-{{ .tlsSecretName }}
  {{- end }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      {{- if .path }}
      - path: {{ printf "%s/%s/" .path $appversion }}api/deliveries(.*)
      {{- else }}
      - path: {{ $defaultversionedpath }}api/deliveries(.*)
      {{- end }}
        backend:
          serviceName: "{{ .serviceName }}-{{ $svcversion }}"
          servicePort: http
      {{- if (eq $appversion "v0.1.0") }}
      - path: {{ default "/" .path }}api/deliveries(.*)
        backend:
          serviceName: "{{ .serviceName }}"
          servicePort: http
      {{- end }}
  {{ end }}
