# QA values for delivery.
nameOverride: delivery
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: Always
    telemetry:
      level: "Information"
    reason: "new qa deploy"
    current: true
    ingress:
      class: "nginx-qa"
    resources:
      requests:
        cpu: 100m
        memory: 350Mi
      limits:
        cpu: 150m
        memory: 500Mi
