# Default values for ingestion.
replicaCount: 1
dockerregistrynamespace:
dockerregistry:
image:
  repository:
  tag:
  pullPolicy: IfNotPresent
reason: unknown
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 80
  initialDelaySeconds: 120
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: /api/probe
    port: 80
  initialDelaySeconds: 120
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 5
telemetry:
  level: "error"
tags:
  dev: false
  prod: false
  qa: false
  staging: false
current: false
