# Production values for dronescheduler.
nameOverride: dronescheduler
exports:
  data:
    replicaCount: 1
    image:
      pullPolicy: IfNotPresent
    telemetry:
      level: "Error"
    reason: "new prod deploy"
    ingress:
      class: "nginx-prod"
    resources:
      requests:
        cpu: 130m
        memory: 350Mi
      limits:
        cpu: 270m
        memory: 500Mi
